kind: pipeline
type: docker
name: build-image-x86_64

steps:
- name: build-image-latest
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/build
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    branch:
    - master

- name: push-image-latest
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/push
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: CONTAINER_IMAGE_REGISTRY_PASSWORD
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    branch:
    - master
    event:
    - push

- name: push-image-tagged
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/push
  environment:
    CONTAINER_IMAGE_VERSION: ${DRONE_TAG}
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: CONTAINER_IMAGE_REGISTRY_PASSWORD
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    branch:
    - master
    event:
    - tag

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock
