kind: pipeline
type: docker
name: build-image-x86_64

steps:
- name: build-image-latest
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/build
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    branch:
    - master

- name: push-image-latest
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/push
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    branch:
    - master

- name: delete-image-latest
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/delete
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    branch:
    - master

- name: push-readme
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make push/README
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    branch:
    - master

- name: notify
  image: drillster/drone-email
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  when:
    status:
    - changed
    - failure

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock
