apiVersion: v1
kind: Pod
metadata:
  name: network-tools
spec:
  containers:
  - name: network-tools
    image: volkerraschek/network-tools:latest
    command: [ "sleep", "3600" ]
    imagePullPolicy: Always
  restartPolicy: Always