apiVersion: v1
kind: Pod
metadata:
  name: network-tools
spec:
  containers:
  - name: network-tools
    image: docker.io/volkerraschek/network-tools:latest
    command: [ "sleep", "3600" ]
    imagePullPolicy: Always
    securityContext:
      capabilities :
        add:
        - NET_ADMIN
        - SYS_TIME
      runAsUser: 1000
  restartPolicy: Always